import './js/header/header';
import './js/burger-menu/burger-menu';
import './js/favorites/favorites';
import './js/categories/categories';
import './js/recipes/recipes';
import './js/rating/rating';
import './js/modal-recipe/modal-recipe';
import './js/dark-theme/dark-theme';
import './js/vanilla-back-to-top/vanilla-back-to-top';